arbitrum:
  rpc: 'https://arb-mainnet.g.alchemy.com/v2/7a5xQqD5uxAPRvpkATRKy1RnzBdpe5Pm'
  chain_id: chain_id
avalanche:
  rpc: 'https://arb-mainnet.g.alchemy.com/v2/7a5xQqD5uxAPRvpkATRKy1RnzBdpe5Pm'
  chain_id: chain_id
private_key: private_key
user_wallet_address: wallet_address
